version: '3'
services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: changeme
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    networks:
      - vikunja
      - database
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s
    ports:
      - "3306:3306"
    networks:
      - database

  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n:5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      # Database
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=n8n
      # db creds
      - DB_USER=n8n
      - DB_PASSWORD=n8n
      # Additional DB settings
      - DB_MAX_CONNECTIONS=20
      - DB_RECONNECT_TRIES=10
      - DB_RECONNECT_TIMEOUT=3000
    networks:
      - vikunja
      - database
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  vikunja:
  database:
    driver: bridge